
version: "2"
services:
  unleash-db:
    container_name: unleash-db
    image: bitnami/postgresql:12
    environment:
      POSTGRES_DB: "unleash"
      POSTGRES_USER: "unleash"
      POSTGRES_PASSWORD: "unleash"
      DISABLE_WELCOME_MESSAGE: "true"
    ports:
      - "5432:5432"
    networks:
      - test
  unleash:
    image: unleashorg/unleash-server:3.6
    container_name: unleash
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: 'postgres://unleash:unleash@unleash-db:5432/unleash'
    networks:
      - test

networks:
  test: